const seedFindings=[
{id:'RS-1042',channel:'social',source:'Instagram',type:'Impersonation',risk:'critical',score:94,status:'open',title:'@acme_robotics_support',subtitle:'Social profile · created 2 days ago',evidence:'Copied logo + “official support” claim',asset:'Acme Robotics logo',confidence:'98%',time:'12 min ago',reasons:['Handle uses the protected brand name with an added support suffix','Profile image is 96% visually similar to the registered Acme mark','Bio links to a payment form outside the official domain'],reach:'18.4K followers',url:'instagram.com/acme_robotics_support'},
{id:'RS-1039',channel:'app',source:'Google Play',type:'App impersonation',risk:'high',score:87,status:'review',title:'Acme Control: Smart Home',subtitle:'Mobile app · publisher “Acme Digital Labs”',evidence:'Similar app name + copied description',asset:'Acme Control / app signature',confidence:'93%',time:'38 min ago',reasons:['App name adds a category phrase to the protected “Acme Control” name','Publisher is not in the official developer register','Description repeats two unique phrases from the legitimate listing'],reach:'4.2K installs',url:'play.google.com/store/apps/acme-control-smart'},
{id:'RS-1037',channel:'social',source:'X / Twitter',type:'Look-alike name',risk:'high',score:82,status:'open',title:'@acme_rob0tics',subtitle:'Social profile · 1.8K followers',evidence:'Character swap in protected name',asset:'@acmerobotics',confidence:'91%',time:'1 hr ago',reasons:['Character swap “o → 0” matches a protected handle pattern','Account uses a near-identical avatar and pinned product claim','Audience and posting cadence are consistent with an active scam profile'],reach:'1.8K followers',url:'x.com/acme_rob0tics'},
{id:'RS-1031',channel:'social',source:'LinkedIn',type:'Fake company page',risk:'high',score:79,status:'escalated',title:'Acme Robotics Careers',subtitle:'Company page · 14 employees',evidence:'Added word + mismatched domain',asset:'Acme Robotics company name',confidence:'89%',time:'3 hrs ago',reasons:['Added word “Careers” creates a look-alike company page','Page redirects applicants to a non-registered domain','Logo treatment differs from the official asset by 14%'],reach:'14 employees',url:'linkedin.com/company/acme-robotics-careers'},
{id:'RS-1028',channel:'app',source:'Apple App Store',type:'App impersonation',risk:'medium',score:66,status:'open',title:'ACME Robotics Remote',subtitle:'Mobile app · publisher “Northstar Apps”',evidence:'Brand phrase + unrecognized publisher',asset:'Acme Robotics app family',confidence:'84%',time:'5 hrs ago',reasons:['Description uses a registered product phrase','Developer is not an official publisher','No official app signature match — review required'],reach:'142 ratings',url:'apps.apple.com/app/acme-robotics-remote'},
{id:'RS-1024',channel:'social',source:'Facebook',type:'Scam profile',risk:'medium',score:61,status:'open',title:'Acme Robotics Deals',subtitle:'Page · 3.4K followers',evidence:'Copied campaign language + external checkout',asset:'Acme Robotics brand identifiers',confidence:'80%',time:'Yesterday',reasons:['Added word “Deals” paired with a copied campaign phrase','Checkout destination is outside the protected domain set'],reach:'3.4K followers',url:'facebook.com/acmeroboticsdeals'},
{id:'RS-1019',channel:'social',source:'Instagram',type:'Look-alike name',risk:'medium',score:59,status:'legitimate',title:'@acme.robotics.team',subtitle:'Social profile · 420 followers',evidence:'Spacing change, but verified partner context',asset:'Acme Robotics name',confidence:'76%',time:'Yesterday',reasons:['Spacing change matches a protected-name variation','Bio clearly identifies an independent robotics community','No copied logo or official claim found — marked legitimate'],reach:'420 followers',url:'instagram.com/acme.robotics.team'},
{id:'RS-1012',channel:'app',source:'Google Play',type:'Suspicious app',risk:'medium',score:54,status:'open',title:'Acme Robot Companion',subtitle:'Mobile app · publisher “Build Boldly LLC”',evidence:'Similar description + logo color match',asset:'Acme Robotics brand identifiers',confidence:'73%',time:'2 days ago',reasons:['Description resembles the official companion app','Logo uses the same ink-blue and brass palette','Publisher is unrecognized and signature is absent'],reach:'89 installs',url:'play.google.com/store/apps/acme-robot-companion'},
{id:'RS-1007',channel:'social',source:'X / Twitter',type:'Mention cluster',risk:'medium',score:48,status:'dismissed',title:'Acme Robotics promo thread',subtitle:'Public thread · 27 posts',evidence:'Brand keyword cluster, low intent',asset:'Acme identifiers',confidence:'68%',time:'3 days ago',reasons:['Keyword cluster is present but no direct impersonation claim','Account history and links are consistent with an independent review'],reach:'6.2K views',url:'x.com/search?q=acme%20robotics'},
{id:'RS-1001',channel:'app',source:'Apple App Store',type:'Look-alike name',risk:'medium',score:45,status:'open',title:'AcmeControl Remote',subtitle:'Mobile app · publisher “Sunset Mobile”',evidence:'Spacing change + publisher mismatch',asset:'Acme Control / app signature',confidence:'71%',time:'4 days ago',reasons:['Spacing change compresses the protected app name','Developer is not in the official publisher register'],reach:'19 ratings',url:'apps.apple.com/app/acmecontrol-remote'},
{id:'RS-0994',channel:'social',source:'LinkedIn',type:'Look-alike name',risk:'medium',score:41,status:'open',title:'Acme Robotics — Global',subtitle:'Company page · 6 employees',evidence:'Added word, no copied logo',asset:'Acme Robotics company name',confidence:'64%',time:'5 days ago',reasons:['Added word expands the protected company name','No official logo match; low confidence keeps this in review'],reach:'6 employees',url:'linkedin.com/company/acme-robotics-global'},
{id:'RS-0988',channel:'app',source:'Google Play',type:'Protected match',risk:'medium',score:22,status:'legitimate',title:'Acme Control',subtitle:'Mobile app · publisher “Acme Robotics Inc.”',evidence:'Exact official match — excluded',asset:'Acme Control / app signature',confidence:'100%',time:'6 days ago',reasons:['Exact official app signature and registered publisher','Automatically excluded from suspicious results'],reach:'12K installs',url:'play.google.com/store/apps/acme-control'}
];
let findings=JSON.parse(localStorage.getItem('riskshield-findings')||'null')||seedFindings;
let profile=JSON.parse(localStorage.getItem('riskshield-profile')||'null')||{company:'Acme Robotics',website:'acmerobotics.com',identifiers:'Acme, Acme Robotics, AR-12, build boldly'};
let currentView='dashboard',demoStep=0,toastTimer;
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function persist(){localStorage.setItem('riskshield-findings',JSON.stringify(findings));localStorage.setItem('riskshield-profile',JSON.stringify(profile))}
function statusLabel(s){return s==='review'?'In review':s[0].toUpperCase()+s.slice(1)}
function findingRow(f,table=false){return `<div class="finding-row" data-id="${f.id}"><div class="finding-severity ${f.risk}">${f.score}</div><div class="finding-title"><strong>${f.title}</strong><span>${f.subtitle}</span></div><div class="finding-evidence"><b>${f.type}</b><br>${f.evidence}</div><div class="finding-source">${f.source}</div><div class="finding-score">${f.confidence}<br><span class="mono">CONF.</span></div>${table?`<div><span class="status-pill ${f.status}">${statusLabel(f.status)}</span></div>`:''}</div>`}
function renderRecent(){const open=findings.filter(f=>['open','review','escalated'].includes(f.status)).sort((a,b)=>b.score-a.score).slice(0,4);$('#recentFindings').innerHTML=open.map(f=>findingRow(f)).join('');}
function filtered(){const q=($('#findingSearch')?.value||'').toLowerCase().trim(),channel=$('#channelFilter')?.value||'all',risk=$('#riskFilter')?.value||'all',status=$('#statusFilter')?.value||'all';return findings.filter(f=>(!q||[f.title,f.subtitle,f.source,f.type,f.evidence].join(' ').toLowerCase().includes(q))&&(channel==='all'||f.channel===channel)&&(risk==='all'||f.risk===risk)&&(status==='all'||f.status===status))}
function renderAll(){const list=filtered();$('#findingCount').textContent=`${list.length} finding${list.length===1?'':'s'}`;$('#allFindings').innerHTML='<div class="finding-row header"><span></span><span>Finding</span><span>Signal</span><span>Source</span><span>Confidence</span><span>Status</span></div>'+list.map(f=>findingRow(f,true)).join('')||'<div class="drawer-empty">No findings match these filters. Try clearing one of the filters.</div>'}
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
function go(view){currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={dashboard:'Overview',findings:'Findings',brand:'Brand profile',architecture:'Architecture',settings:'Workspace settings'};$('#pageCrumb').textContent=names[view];window.scrollTo({top:0,behavior:'smooth'});if(view==='findings')renderAll()}
function openDrawer(id){const f=findings.find(x=>x.id===id);if(!f)return;$('#drawerContent').innerHTML=`<div class="drawer-kicker">${f.id} / ${f.source.toUpperCase()} / ${f.time.toUpperCase()}</div><h2 class="drawer-title">${f.title.includes('@')?f.title.replace('@','<em>@</em>'):f.title}</h2><div class="drawer-status-row"><span class="status-pill ${f.status}">${statusLabel(f.status)}</span><span class="finding-severity ${f.risk}">${f.score} RISK</span><span class="health healthy">${f.confidence} confidence</span></div><div class="drawer-section"><h3>Signal summary</h3><p>${f.evidence}. RiskShield matched this signal to <strong>${f.asset}</strong> and kept it visible because the source is ${f.source.toLowerCase()}.</p><div class="drawer-evidence"><div class="evidence-cell"><span>Estimated reach</span><strong>${f.reach}</strong></div><div class="evidence-cell"><span>Detection type</span><strong>${f.type}</strong></div><div class="evidence-cell"><span>First seen</span><strong>${f.time}</strong></div><div class="evidence-cell"><span>Source link</span><strong>${f.url}</strong></div></div></div><div class="drawer-section"><h3>Why it earned attention</h3><ul class="reason-list">${f.reasons.map(r=>`<li>${r}</li>`).join('')}</ul></div><div class="drawer-section"><h3>Analyst note</h3><textarea class="note-input" id="noteInput" placeholder="Add context for your team…">${f.note||''}</textarea></div><div class="drawer-section"><div class="drawer-actions"><button class="button primary" data-action="review" data-id="${f.id}">Mark in review</button><button class="button ghost" data-action="legitimate" data-id="${f.id}">Mark legitimate</button><button class="button ghost" data-action="escalated" data-id="${f.id}">Escalate</button><button class="button ghost" data-action="dismissed" data-id="${f.id}">Dismiss</button><button class="button ghost" data-action="save-note" data-id="${f.id}">Save note</button></div></div>`;$('#drawerBackdrop').classList.add('open')}
function closeDrawer(){$('#drawerBackdrop').classList.remove('open')}
function updateStatus(id,status){const f=findings.find(x=>x.id===id);if(!f)return;f.status=status;persist();renderRecent();renderAll();openDrawer(id);showToast(`${id} marked ${statusLabel(status).toLowerCase()}.`)}
function showDemo(){demoStep=0;renderDemo();$('#modalBackdrop').classList.add('open')}
const demoData=[{label:'01 FIND',title:'A signal appears.',copy:'RiskShield surfaces a profile using a one-character swap in the protected Acme Robotics handle — before it becomes a customer support problem.',evidence:'@acme_rob0tics',detail:'X / Twitter · 1.8K followers · 82 risk score'},{label:'02 UNDERSTAND',title:'The evidence is legible.',copy:'The match is not a black-box label. The engine shows the character swap, copied avatar, and unusual posting pattern that created the score.',evidence:'Character swap “o → 0”',detail:'91% confidence · matched @acmerobotics'},{label:'03 ACT',title:'The decision stays yours.',copy:'Review, escalate, mark legitimate, or dismiss — with a note that makes the next analyst faster. Official assets never enter the suspicious queue.',evidence:'Escalate to brand protection',detail:'Action logged · workspace state saved'}];
function renderDemo(){const d=demoData[demoStep];$('#demoStepLabel').textContent=d.label;$('.demo-progress i').style.width=`${(demoStep+1)*33.33}%`;$('#demoBody').innerHTML=`<h2>${d.title}</h2><p>${d.copy}</p><div class="demo-evidence"><span class="mono">EVIDENCE / ${d.label}</span><strong>${d.evidence}</strong><span>${d.detail}</span></div>`;$('#demoBack').style.visibility=demoStep?'visible':'hidden';$('#demoNext').innerHTML=demoStep===2?'Close demo <span>×</span>':'Continue <span>→</span>'}
function bind(){ $$('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-view-link]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.viewLink)));$$('[data-demo-start]').forEach(b=>b.addEventListener('click',showDemo));$('#modalClose').addEventListener('click',()=>$('#modalBackdrop').classList.remove('open'));$('#demoNext').addEventListener('click',()=>{if(demoStep===2){$('#modalBackdrop').classList.remove('open');showToast('Demo complete — you are ready to triage.')}else{demoStep++;renderDemo()}});$('#demoBack').addEventListener('click',()=>{if(demoStep>0){demoStep--;renderDemo()}});$('#drawerClose').addEventListener('click',closeDrawer);$('#drawerBackdrop').addEventListener('click',e=>{if(e.target.id==='drawerBackdrop')closeDrawer()});document.addEventListener('click',e=>{const row=e.target.closest('.finding-row[data-id]');if(row)openDrawer(row.dataset.id);const action=e.target.closest('[data-action]');if(action){const id=action.dataset.id;if(action.dataset.action==='save-note'){const f=findings.find(x=>x.id===id);f.note=$('#noteInput').value;persist();showToast('Analyst note saved to the workspace.')}else updateStatus(id,action.dataset.action)}});['#findingSearch','#channelFilter','#riskFilter','#statusFilter'].forEach(s=>$(s)?.addEventListener('input',renderAll));$('#clearFilters').addEventListener('click',()=>{$('#findingSearch').value='';$('#channelFilter').value='all';$('#riskFilter').value='all';$('#statusFilter').value='all';renderAll();showToast('Filters cleared.')});$('#profileForm').addEventListener('submit',e=>{e.preventDefault();profile={company:$('#companyName').value,website:$('#website').value,identifiers:$('#identifiers').value};localStorage.setItem('riskshield-profile',JSON.stringify(profile));$('#profileOrgLabel').textContent=profile.company;$('#saveState').textContent='Saved just now';showToast('Brand profile saved — official asset boundary updated.')});$('#profileOrgLabel').textContent=profile.company;$('#companyName').value=profile.company;$('#website').value=profile.website;$('#identifiers').value=profile.identifiers;$('#assetCount').textContent='24';$$('[data-scroll-form]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#profileForm')?.scrollIntoView({behavior:'smooth'})))}
renderRecent();bind();
